import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const packageInfo = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const [major, minor, basePatch] = packageInfo.version.split('.').map(Number);

// Version 1.3.2 lands in commit 84. Each later commit advances the patch version.
const baselineCommitCount = 84;
let commitCount = baselineCommitCount;

try {
  commitCount = Number(
    execFileSync('git', ['rev-list', '--count', 'HEAD'], {
      cwd: root,
      encoding: 'utf8',
    }).trim(),
  );
} catch {
  console.warn('Git history unavailable; using the package version.');
}

const patch = basePatch + Math.max(0, commitCount - baselineCommitCount);
const version = `${major}.${minor}.${patch}`;
const outputPath = resolve(root, 'src/app/generated-version.ts');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/generate-version.mjs. Do not edit.\nexport const APP_VERSION = '${version}';\n`,
);

console.log(`Application version: ${version}`);
