import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const packageInfo = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const version = packageInfo.version;
const outputPath = resolve(root, 'src/app/generated-version.ts');

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(
  outputPath,
  `// Generated by scripts/generate-version.mjs. Do not edit.\nexport const APP_VERSION = '${version}';\n`,
);

console.log(`Application version: ${version}`);
